server {
    listen 80;
    listen [::]:80;
    server_name madtec.org;

    root /home/soulwax/workspace/other/dyndns/www;
    index index.html;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    access_log /var/log/nginx/madtec.access.log;
    error_log  /var/log/nginx/madtec.error.log;
}
